"""empty message

Revision ID: 9263576e50f1
Revises: 545e5a804fd2
Create Date: 2025-02-02 01:11:22.111303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9263576e50f1'
down_revision: Union[str, None] = '545e5a804fd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Categories', 'CategoryName',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('GameAccounts', 'UserID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('GameAccounts', 'AccountIdentifier',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('GameAccounts', 'Balance',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('Items', 'Name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Items', 'Description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('Items', 'Price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('Items', 'CategoryID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Items', 'Status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('Notifications', 'UserID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Notifications', 'Message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('Notifications', 'SendDate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('OrderItems', 'OrderID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('OrderItems', 'ItemID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('OrderItems', 'Quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Orders', 'UserID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Orders', 'CreationDate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('Orders', 'Status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Payments', 'OrderID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Payments', 'PaymentMethod',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Payments', 'Amount',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('Payments', 'Status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('PurchaseHistory', 'UserID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('PurchaseHistory', 'ItemID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('PurchaseHistory', 'PurchaseDate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('Users', 'Username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Users', 'PasswordHash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Users', 'Email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Users', 'RegistrationDate',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('Users', 'createdAt')
    op.drop_column('Users', 'updatedAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('updatedAt', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('Users', sa.Column('createdAt', sa.DATE(), autoincrement=False, nullable=False))
    op.alter_column('Users', 'RegistrationDate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('Users', 'Email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Users', 'PasswordHash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Users', 'Username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('PurchaseHistory', 'PurchaseDate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('PurchaseHistory', 'ItemID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('PurchaseHistory', 'UserID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Payments', 'Status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Payments', 'Amount',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('Payments', 'PaymentMethod',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Payments', 'OrderID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Orders', 'Status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Orders', 'CreationDate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('Orders', 'UserID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('OrderItems', 'Quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('OrderItems', 'ItemID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('OrderItems', 'OrderID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Notifications', 'SendDate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('Notifications', 'Message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('Notifications', 'UserID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Items', 'Status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('Items', 'CategoryID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Items', 'Price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('Items', 'Description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('Items', 'Name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('GameAccounts', 'Balance',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('GameAccounts', 'AccountIdentifier',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('GameAccounts', 'UserID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Categories', 'CategoryName',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
